### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by jcxplorer** [stripe/stripe-mock#11]
Are there any plans to make it possible to use this as a library in a Go project? Would be fantastic to be able to launch the HTTP server in tests.

Only had a quick look through the code, but it seemed like exporting the StubServer fields might even be enough to achieve this?

**Comment by brandur-stripe** [comment]
I thought about it, but punted for now just because I was mostly running it from other languages. It's good to know there's demand though! I'll see what I can do.

**Comment by brandur-stripe** [comment]
Thinking about this one a bit more — I think it's a good idea to provide this, but we should aim to export as small of an interface as possible so that we can enable future changes.

Maybe something like this:

``` go
import "github.com/stripe/stripe-mock/server"

mock, err := server.NewMockServer()
http.HandleFunc("/", mock.HandleRequest)
```

The bundled OpenAPI spec and fixtures are always used.

We're putting through a fairly major refactor to put this project onto OpenAPI 3.0 right now, but we should look into tackling this afterwards. Tagging it as "future" for the time being.

**Comment by jeffawang** [comment]
I was able to kludge something together after messing with import paths and packages. As mentioned, just exporting the StubServer seemed to do the trick. Being able to use `httptest` and whatnot while testing is quite nice.

**Comment by supermarin** [comment]
It seems like this was done in #265 .
Related issue: #206 

@richardm-stripe is there a chance you could add some docs on how to use this?

**Comment by supermarin** [comment]
Looks like this comment is still relevant and it works:
https://github.com/stripe/stripe-mock/pull/238#issuecomment-876041944

**Comment by anniel-stripe** [comment]
Closing, was fixed in https://github.com/stripe/stripe-mock/pull/265
