### ISSUE TITLE
Invoicing Support?

### ISSUE THREAD

**Issue by kr4ster** [stripe/stripe-mock#116]
One of the toughest things for us to test currently is invoicing.  Primarily because most invoicing processes are initiated by Stripe.  It would be very helpful to, at the very least, make a call to the mock requesting that it call an endpoint to initiate an invoicing event (e.g. invoice_created).

**Comment by brandur-stripe** [comment]
Okay, I'm not sure that we'll get to this kind of thing right away, but that sounds like a very interesting feature. I'll leave this issue open for tracking.

**Comment by anniel-stripe** [comment]
Hello, apologies for the very late update here! I'm closing this issue out as out of scope, since we do not plan to expand stripe-mock functionality past that of a basic validation tool. You can refer to [our updated README](https://github.com/stripe/stripe-mock#future-plans), which details our future plans for stripe-mock.
