### ISSUE TITLE
Use test card numbers and tokens in the mock

### ISSUE THREAD

**Issue by qrush** [stripe/stripe-mock#158]
I was surprised that Stripe's own test tokens for invalid cards, etc aren't supported by this mock out of the box. I feel like supporting this should be a bit higher in the priority list than storing data locally:

https://stripe.com/docs/testing#cards

**Comment by brandur-stripe** [comment]
Yeah, I'd like to support these. Two major reasons that it's note done already:

* All stripe-mock endpoints are powered by OpenAPI and don't have specific implementations right now. Implementing the test card numbers would be a deviation from that.
* Without OpenAPI, we don't really have a way of keeping the test numbers in use here in sync with what the Stripe API offers.

We should still do it, but it may take a little time yet. Marking as "future" for now.

**Comment by adrienverge** [comment]
@qrush while waiting for the official stripe-mock to support these, you could use [localstripe](https://github.com/adrienverge/localstripe): it implements invalid cards handling, attaching errors, payment errors, etc.

**Comment by anniel-stripe** [comment]
Hello, sorry for the very late update here! Similar to https://github.com/stripe/stripe-mock/issues/19, I'm closing this issue out as out of scope, since we do not plan to expand stripe-mock functionality past that of a basic sanity check tool. You can refer to [our updated README](https://github.com/stripe/stripe-mock#future-plans), which details our future plans for stripe-mock.
