### ISSUE TITLE
Returned association ids are the same for every request

### ISSUE THREAD

**Issue by tristanoneil** [stripe/stripe-mock#180]
We have run into an issue similar to https://github.com/stripe/stripe-mock/issues/152 but for the ids of associations. Our database has a unique constraint on a column where we're storing the `charge.id` from a `payment_intent`. This constraint makes it so we cannot use `stripe-mock` in cases where we take two actions that result in persisting a record with this column as the `charge.id` is always the same.

**Comment by brandur-stripe** [comment]
We could probably patch this by having a heuristic like:

1. For IDs found in incoming parameters, replace whatever would have appeared in the response with those incoming (e.g. if `plan=plan_123` is sent to to `POST /v1/subscriptions`, the returned `plan` field should be `plan_123`).
2. Randomize all other IDs.

This is a little more questionable than the solution to #152 because unlike there where we expect the create endpoint to generate a new ID anyway, fields like `charge.id` are supposed to represent a pre-existing object. Still, as long as stripe-mock isn't persistent, this probably doesn't matter.

**Comment by tristanoneil** [comment]
Option 2 would work for at least our current use case.

At least in the case of payment intents given that the `id` is unique each time I think it'd make sense for the `charge.id` to also be unique each time as the real API doesn't associate the same charge with multiple unique payment intents (or at least I don't think it does 😄).

**Comment by brandur-stripe** [comment]
I tried to see if I could implement this one quickly, but there turned out to be a few more problems than I was hoping for. The biggest one is that currently we don't actually know whether a field is an ID or not when responding from the generator — often ID fields are called `id`, but they're also often called things like `charge`.

The information is sort of in the OpenAPI spec, but not in a way that I'd call "reliably". Usually ID fields are expandable, which is marked, but I don't think every ID field is expandable so it's not a complete solution.

I could also try to match on some ID like pattern like `[a-z]{2,6}_{A-Za-z0-9]{10,}`, and although it'd probably work mostly, I'm not too crazy about these sorts of systems that don't have a definitive way of always working reliably.

Unfortunately, I think the better plan might be to put something in that's a little more elaborate as part of something like #19 that we can be sure always makes the right decisions all the time.

**Comment by tristanoneil** [comment]
@brandur-stripe curious if there are any plans within Stripe to focus on moving forward with #19. We had previously been using `stripe-ruby-mock` but newer API endpoints aren't very well supported so we've been struggling to find a path forward for testing our integration at the system level.
