### ISSUE TITLE
default_tax_rates in subscription endpoint has the wrong type

### ISSUE THREAD

**Issue by sauroter** [stripe/stripe-mock#210]
Hi,

When testing the Java SDK against the mock server a call to  create a subscription (`POST http://mockserver/v1/subscriptions`) and setting the `default_tax_rates` parameter to a tax rate id (e.g. txr_123), the mockserver returns an subscription object containing a list of strings as `default_tax_rates` instead of an list of tax_rates (https://stripe.com/docs/api/subscriptions/object?lang=curl#subscription_object-default_tax_rates). 

This obviously leads to a JSON parse exception in the SDK.

Greetings
Georg

**Comment by ob-stripe** [comment]
Hi @sauroter, thanks for the report.

@brandur-stripe I think this is caused by stripe-mock's "mirroring" feature where if a parameter is passed and the response has a field with the same name, then stripe-mock will fill the response field with the parameter's value.

This only works if the response field has the same shape as the request parameter, which is not always the case. In this case the [`default_tax_rates`](https://stripe.com/docs/api/subscriptions/create#create_subscription-default_tax_rates) parameter is a list of strings, but the [`default_tax_rates`](https://stripe.com/docs/api/subscriptions/object#subscription_object-default_tax_rates) field is a list of objects.

Since stripe-mock should know the shape of both the parameter and the field from the OpenAPI spec, ideally it would only copy the value if the shape is identical, but I don't know how hard that would be. Can you take a look?

**Comment by brandur-stripe** [comment]
Thanks @ob-stripe! I _think_ we do something a little like that already somewhere (I can't remember the specifics) so it shouldn't be too hard. I'll look into it.

**Comment by brandur-stripe** [comment]
A fix should now be available in 0.80.0.

**Comment by sauroter** [comment]
Wow, you are amazing!
Thank you for the fast work.
