### ISSUE TITLE
Creating a customer with a source does not echo the default_source in response

### ISSUE THREAD

**Issue by mahirk** [stripe/stripe-mock#214]
Creating a customer with a source does not respond with the default source as part of the response. The response seems to have a `source ` object as an alipay account. 

As an option for implementation, the API can accept source parameter as `tok_visa` and use those values, which handles only the basic. Any other values in source can respond with the same value right now, with the `alipay` as the source and default source (if the source object is passed)

**Comment by brandur-stripe** [comment]
Hey @mahirk, yeah this is a known limitation — stripe-mock is fairly dumb right now in that rather than encompassing the more sophisticated domain logic of Stripe's real API, all it does is bundle an OpenAPI specification to map out possible endpoints/parameters and a set of fixtures that represent a sample of what any of those endpoints might return.

It tries a few tricks by modifying the outgoing response according to input parameters, but only for simple heuristics. e.g. Both request/response had a parameter/field of the same name, and that field's type matched across both.

See "current state of development" here for some more information:
https://github.com/stripe/stripe-mock#current-state-of-development

**Comment by mahirk** [comment]
Thanks @brandur-stripe! I'll close out this issue, I had tried to parse through fixtures in the open-api spec to see if there were any updates that could be made to that area. I noticed that the spec only returns back the default source when expanded, and also has a polymorphic schema for the `default_source`. Is there a way to force it to return the value for the `card`, as `default_source`, or would it always only be the `alipay` account?

**Comment by brandur-stripe** [comment]
> Is there a way to force it to return the value for the `card`, in `source`, or would it always only be the `alipay` account? [Specifically in the POST request]

Yeah, sorry, basically what it's doing in this case is just pulling in the source fixture and putting it into that `source` field without any notion as to what came in via parameter.

stripe-mock is most useful for verifying that endpoints and parameters sent to them are valid, and it tries to send back a valid looking response, but that response will be largely nonsense, and mostly invariant of the input. To maximize the fidelity of your tests it might be best to implement some kind of hybrid solution — use stripe-mock by default, but anywhere a response actually matters, intercept what it returns and replace it with something more sensible.

**Comment by mahirk** [comment]
Understood, thank you for the assistance @brandur-stripe!
