### ISSUE TITLE
additional properties are not allowed: name

### ISSUE THREAD

**Issue by liemdo** [stripe/stripe-mock#219]
Hi,

I get this error when running test but everything works fine on production:

`Request validation error: validator 0xc4209aa930 failed: additional properties are not allowed: name`

My code is quite simple:

```javascript
const stripeParams = {
 name: 'Customer',
 email: 'test@example.com'
};

stripe.customers.create(stripeParams);
```

**Comment by ob-stripe** [comment]
@liemdo Are you using the latest version?

**Comment by liemdo** [comment]
I'm using the latest docker image stripemock/stripe-mock (image id: c083294139fb)

**Comment by brandur-stripe** [comment]
Can you try hitting the Docker image directly with cURL? Something like this:

```
curl http://localhost:12111/v1/customers -i -X POST -u sk_test_123: -d "name=foo"
```

If this doesn't work, can you take a look at the `Stripe-Mock-Version` header that comes back? My best guess is that you have an old version of stripe-mock running in a place you didn't expect and are hitting that instead of the Docker image.

```
$ curl http://localhost:12111/v1/customers -i -X POST -u sk_test_123: -d "name=foo"
HTTP/1.1 200 OK
Request-Id: req_123
Stripe-Mock-Version: 0.80.0
Date: Fri, 06 Mar 2020 23:55:32 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked

{
  "address": null,
  "balance": 0,
  "created": 1234567890,
```
