### ISSUE TITLE
Validator failure on payment_method_data

### ISSUE THREAD

**Issue by DawidJanczak** [stripe/stripe-mock#231]
Hello,

We're trying to use stripe-mock in our integration tests (behind `mock-server`) and are running into the following:
```
Request validation error: validator 0xc000f63ad0 failed: additional properties are not allowed: payment_method_data, expected_payment_method_type, key
```
on a `Request: POST /v1/payment_intents/pi_<snip>/confirm` endpoint. Originally I thought it's because of an outdated API, but we just upgraded and are still getting this error. We use the following method to confirm our payment intent (CoffeeScript):
```
stripe.confirmCardPayment(
  clientSecret
  payment_method:
    card: cardElement
    billing_details:
      name: cardholderName.value
    ).then(...)
```
as described in https://stripe.com/docs/js/payment_intents/confirm_card_payment

I have confirmed that the same params are being sent to Stripe on a successful payment. Not sure what's wrong here and would appreciate some input. Thanks!

**Comment by remi-stripe** [comment]
@DawidJanczak Thanks for reaching out! This one is kind of on purpose as this call would be sending raw card details to our API which is something we strongly discourage for Security and PCI compliance reasons. So while it works in the API, it's not something we actively document today to ensure most integrations don't do this unless they have the right level of PCI compliance.

Since stripe-mock ingests our public openapi spec, it would support passing `payment_method_data[type]=sepa_debit` for example but not `card`.

For that one call, since you're trying to simulate a client-side call I'd recommend just mocking the call entirely.

**Comment by DawidJanczak** [comment]
Thanks for the explanation @remi-stripe. This is a bit out of scope for this library I suppose, but I'd like to ask a follow-up question if that's OK. Given we have to fetch `stripe.js` from Stripe servers anyway (which makes our tests dependent on internet connection) do you think it would be OK to hit Stripe servers on this endpoint as well, using the fake card data? I would have thought it's inadvisable, but the last paragraph in https://github.com/stripe/stripe-mock#future-plans seems to imply that it's fine.

**Comment by remi-stripe** [comment]
That seems fine if you use our [test card numbers](https://stripe.com/docs/testing#cards) in Test mode though I'd still recommend just mocking that part of your integration to avoid relying on an internet connection for your automated test suite. But I don't see why it'd be an issue overall as long as you don't hammer the API too often during the test suite's runs (which we have rate limits against already)!
