### ISSUE TITLE
subscription creation missing plan in v0.95.0

### ISSUE THREAD

**Issue by ethanrubio** [stripe/stripe-mock#234]
Creating a plan and attaching to a new subscription in v0.94.0 attaches a plan to the subscription response. However, in v0.95.0, creating a plan and attaching to a new subscription in v0.95.0 no longer has the plan information in it even though it is successfully created. I noticed the plan ids generated are completely different too from v0.94.0 to v0.95.0.

```
// v0.94.0
Request: POST /v1/plans
Request data = map[amount:1000 currency:usd interval:month nickname:testID-month-1000 product:prod_HGKvJMV3UfOYPf]
Response: elapsed=374.2µs status=200
Request: POST /v1/subscriptions
Request data = map[customer:testID default_payment_method:pm_id items:[map[plan:gold_F8pssb9wsZpgsxT]] metadata:map[userID:] proration_behavior:none]
Response: elapsed=507.9µs status=200
```

```
// v0.95.0
Request: POST /v1/plans
Request data = map[amount:1000 currency:usd interval:month nickname:testID-month-1000 product:prod_HGKvJMV3UfOYPf]
Response: elapsed=272.2µs status=200
Request: POST /v1/subscriptions
Request data = map[customer:testID default_source:ba_id items:[map[plan:price_F8pqplUBG5bRLKI]] metadata:map[userID:] proration_behavior:none]
Response: elapsed=358.4µs status=200
```

**Comment by remi-stripe** [comment]
@ethanrubio Thanks for reaching out! The `plan` property top-level on `Subscription` has been considered deprecated for multiple years since we added support for multiple plans on a Subscription. The problem with `plan` top-level was that it only worked if you only ever had one plan, otherwise it was null. The idea is that you should instead look at `items.data[0].plan` instead.

Similarly, the `Plan` API is considered deprecated as we introduced the `Price` API to replace it. All Plan objects work as Price objects and vice versa which makes it a lot easier to migrate. We haven't yet marked the resource as deprecated and it will work for years to come but we do want to slowly de-emphasize the more legacy paths/resources so that new developers and developers integrating new features always refer to the most recent version of the API instead. So in that same vein, what you really should be looking at is `items.data[0].price` as documented [here](https://stripe.com/docs/api/subscriptions/object#subscription_object-items-data-price).

Yesterday when I release the new stripe-mock, it removed support for `plan` top-level because this property has been officially undocumented from our API this week. It still works and we haven't broken any existing integration we just want to discourage its usage.

Does this help clarify what happened and does it unblock you?

**Comment by ethanrubio** [comment]
@remi-stripe ok makes sense. thanks for quick reply and the clarification!
