### ISSUE TITLE
Regarding using mock stripe for e2e tests

### ISSUE THREAD

**Issue by devansh-dalal** [stripe/stripe-mock#247]
I am planning to use stripe-mock for local e2e testing in our app,

```
public PaymentMethod createPaymentMethod(Card card) {
      var paymentMethodParams =
          PaymentMethodCreateParams.builder()
              .setType(Type.CARD)
              .setCard(
                  CardDetails.builder()
                      .setNumber(card.getNumber())
                      .setExpMonth((long) card.getExpiryMonth())
                      .setExpYear((long) card.getExpiryYear())
                      .setCvc(card.getCvv())
                      .build())
              .build();
      var response = testMode? "Make API call to mock stripe with params" : PaymentMethod.create(paymentMethodParams);
      return response;
  }
```

Now I do not want to manually make http call to stripe mock server(`localhost:`) with http client and request body, Is there a way to change something in `RequestOptions` or use a different dependency to make the call?

Basically, I don't want to do, something equivalent of

```
String url = String.format("%s%s", Stripe.getApiBase(), String.format("/v1/payment_methods/%s", ApiResource.urlEncodeId(paymentMethod)));
(Customer)ApiResource.request(RequestMethod.GET, url, params, Customer.class, options);
```

just somehow override the stripe base API URL.

`Stripe.overrideApiBase();` is something useful, but its static to stripe java library, I want normal stripe calls to go through, when my e2e tests are running.

**Comment by remi-stripe** [comment]
@devansh-dalal Some of our client libraries support overriding the api base on a per request basis but stripe-java is unfortunately not one of those today. We would like to add the ability to do this on a per-request basis in the future but that will likely only happen once we ship a client/service infrastructure in the library like we did in stripe-php [here](https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0).

The only way is to override this globally in your test suite itself for all your tests today. This shouldn't impact your production environment though as they should run on a different environments right? Otherwise, you would need to do the raw call as you mentioned above.

**Comment by devansh-dalal** [comment]
`environment though as they should run on a different environments right?`

yes, in theory, but we also run e2e tests on prod as a final validation before promoting a new release.

ok, so, do you think you can recommend any other client library to make api calls with mock stripe. I don't feel comfortable manipulating raw http requests

**Comment by remi-stripe** [comment]
@devansh-dalal I don't know of any other library to support this today unfortunately. Any kind of mock you put in place will require changing the `api_base` in stripe-java if you want your live environment to run those requests. I don't think I've seen a setup like this before either where you expect to mock production calls so I'm can't think of an alternative here beyond forking the library.

**Comment by devansh-dalal** [comment]
thanks and no worries. @remi-stripe , do you think I should raise this issue in https://github.com/stripe/stripe-java? I am comfortable for this to be picked up in later stripe versions.

**Comment by remi-stripe** [comment]
Sure that won't hurt though I know we won't ship this soon. At least not until we re-design the library to do client/services instead. It's on our roadmap but no firm timeline just yet. 
I'm going to close the bug here since it's not really specific to stripe-mock and we can tag your other request on stripe-java as "future"!
