### ISSUE TITLE
current_phase is null in subscription schedules fixture

### ISSUE THREAD

**Issue by jgaiser-alto** [stripe/stripe-mock#444]
https://github.com/stripe/stripe-mock/blob/1f05c0034db7407b9d77724f532f508ead46a1fb/embedded/openapi/fixtures3.json#L2995

[current_phase docs](https://stripe.com/docs/api/subscription_schedules/object#subscription_schedule_object-current_phase) seem to imply this would only be null if the schedule is not `active`. I think it would be a more useful for the mock to respond as if the schedule was active.

**Comment by anniel-stripe** [comment]
Hi @jgaiser-alto, as mentioned in the response in https://github.com/stripe/stripe-mock/issues/376, stripe-mock does not carry state, so there only exists one hardcoded response for each endpoint. The `subscription_schedule` response represents one that will start in the future where `current_phase` is null. As stripe-mock is meant to serve as a basic request validation tool, we don't recommend relying on its responses to mimic real API behavior.

I'll be closing this issue out as not planned, since stripe-mock is in maintenance mode and we don't plan to add state to stripe-mock (see https://github.com/stripe/stripe-mock#future-plans).
