### ISSUE TITLE
The status code returned by the createSetupIntent API does not match the actual behavior of the API when called in the test environment.

### ISSUE THREAD

**Issue by larryro** [stripe/stripe-mock#554]
Hi, when calling the `createSetupIntent` API, I set the confirm parameter to true and included the paymentmethod's id. In the testing environment, the status code will directly return `SUCCEEDED`, but in the mock environment, it returns `REQUIRES_PAYMENT_METHOD`.

params for `createSetupIntent`:
```
{
      customer: 'cus_LnXUv4g1CxPpKt3',
      payment_method: 'pm_LnXVDJjNBcoaLpj',
      confirm: true,
      usage: 'off_session',
      automatic_payment_methods: { enabled: true, allow_redirects: 'never' }
 }
```

**Comment by remi-stripe** [comment]
@larryro this is expected behaviour. stripe-mock is not used to mimic/reproduce the real behavior of the API but instead to return responses that describe the right objects to simplify testing. It's covered in a bit more details in the readme [here](https://github.com/stripe/stripe-mock#features-and-limitations). You will need to override the responses to match what you need in cases like this.
