### ISSUE TITLE
/v1/payment_intents/:payment_intent_id/confirm payment_method_data doesn't have property "card"

### ISSUE THREAD

**Issue by RuslanRamazanov72** [stripe/stripe-mock#706]
Hello, I'm running the Stripe mock server in Azure Cloud with the latest version, v0.182.0, and I couldn't send the exact same request that we're performing in production `/v1/payment_intents/:payment_intent_id/confirm`. When I tried to send POST request with `payment_method_data[type]=card` it throws validation "value is not in enumeration" error. Then, I found a [openai json spec](https://raw.githubusercontent.com/stripe/stripe-mock/master/embedded/openapi/spec3.beta.sdk.json) in this repo where I was able to find out properties of `payment_method_data`  
x.paths["/v1/payment_intents/{intent}/confirm"].post.requestBody.content["application/x-www-form-urlencoded"].schema.properties.payment_method_data.properties

and noticed that there's no `card` type for `payment_method_data`. 
Is that `card` type available in any other mock versions?

**Comment by remi-stripe** [comment]
@RuslanRamazanov72 The ability to pass raw card details server-side is not supported in our public API. You need approval and a custom setting on your account to be able to use this. For that reason it's not in our API Reference or our OpenAPI spec at the moment and stripe-mock will not support it.
In almost all cases you should be collecting card details client-side in the first place using [Elements](https://stripe.com/docs/payments/elements#elements) for example. For unit tests you can pass `payment_method: 'pm_card_visa'` or equivalent to simulate card collection client-side.

Otherwise if you want to send raw card details and your account has the feature then you'll have to skip stripe-mock entirely for this and instead mock locally in your own test suite.
