### ISSUE TITLE
About the limitations

### ISSUE THREAD

**Issue by khanhmas** [stripe/stripe-mock#711]
I tried to create an account with a personalized settings about payouts.schedule.interval, transfer, etc. but these parameters are not reflected in the response (just like you said that all responses are hardcoded in stripe-mock).

Please let me know if there will be some improvements about this aspect in the future.

**Comment by remi-stripe** [comment]
@khanhmas we don't have plans to change or improve this in the future. The stripe-mock library is really seen as a way to quickly mock the API and get a valid response describing a certain object. It doesn't maintain state or treat parameters a certain way. Otherwise we'd have to rebuild most of the logic of the API in stripe-mock

For cases like yours you should mock the JSON response yourself in your tests instead.
